import com.vanniktech.maven.publish.JavaLibrary
import com.vanniktech.maven.publish.JavadocJar
import com.vanniktech.maven.publish.SourcesJar

plugins {
    java
    id("com.vanniktech.maven.publish") version "0.36.0"
}

java {
    // JDK 17 MSRV.
    toolchain { languageVersion.set(JavaLanguageVersion.of(17)) }
}

repositories { mavenCentral() }

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Workspace root is two levels up from bindings/jvm.
val workspaceRoot = layout.projectDirectory.dir("../..").asFile
val resourcesNativeRoot = layout.projectDirectory.dir("src/main/resources/native")

// Triples that MUST be present in the assembled fat JAR (match ci.yml's build
// matrix). macos-x86_64 (Intel) is deferred — see docs/deferred-features.md.
val gatingTriples = listOf("linux-x86_64", "linux-aarch64", "macos-aarch64", "windows-x86_64")

// When set (CI assemble job), skip cargo and stage pre-built libs from this dir
// (expected layout: <dir>/native/<triple>/libtstjni.<ext>). When null (dev),
// build the current platform's cdylib via cargo.
val nativeStagingDir = project.findProperty("nativeStagingDir") as String?

// When true (-PjniTestHooks=true), build the cdylib with the `jni-test-hooks`
// cargo feature so the test-only panic probe symbol is present, and enable the
// @EnabledIfSystemProperty-gated PanicIsolationTest. Default-OFF; the shipped
// JAR is always built probe-free (CI rebuilds without this before staging).
val jniTestHooks: Boolean = (project.findProperty("jniTestHooks") as String?)?.toBoolean() ?: false

// Resolve the running host to the canonical <os>-<arch> triple that
// NativeLoader.triple() produces at runtime. MUST stay in sync with
// NativeLoader.triple() — any os/arch normalization change there must be
// mirrored here, or dev-mode staging puts the lib in the wrong dir and tests
// fail with UnsatisfiedLinkError.
fun currentTriple(): String {
    val os = System.getProperty("os.name").lowercase()
    val arch = System.getProperty("os.arch").lowercase()
    val o = when {
        os.contains("win") -> "windows"
        os.contains("mac") || os.contains("darwin") -> "macos"
        else -> "linux"
    }
    val a = when (arch) {
        "amd64", "x86_64" -> "x86_64"
        "aarch64", "arm64" -> "aarch64"
        else -> arch
    }
    return "$o-$a"
}

// cargo's cdylib basename differs by OS: tstjni.dll on Windows (no lib prefix),
// libtstjni.dylib on macOS, libtstjni.so on Linux.
fun cargoLibName(triple: String): String = when {
    triple.startsWith("windows") -> "tstjni.dll"
    triple.startsWith("macos") -> "libtstjni.dylib"
    else -> "libtstjni.so"
}

// JAR resource name: ALWAYS libtstjni.<ext> on every platform (NativeLoader
// expects the lib prefix everywhere; Windows tstjni.dll is renamed on copy).
fun resourceLibName(triple: String): String = when {
    triple.startsWith("windows") -> "libtstjni.dll"
    triple.startsWith("macos") -> "libtstjni.dylib"
    else -> "libtstjni.so"
}

// --- Dev mode: build current platform's cdylib (release) via cargo. This
//     links vendored libsrt + mbedTLS, so SRT_FORCE_VENDORED=1 is
//     required; the first cold build compiles libsrt (~3-5 min), warm is seconds.
val cargoBuild = tasks.register<Exec>("cargoBuild") {
    onlyIf { nativeStagingDir == null }
    workingDir = workspaceRoot
    environment("SRT_FORCE_VENDORED", "1")
    val cargoCmd = mutableListOf("cargo", "build", "--release", "-p", "tst-jni")
    if (jniTestHooks) {
        // Build the test-only panic probe symbol into the cdylib.
        cargoCmd.addAll(listOf("--features", "jni-test-hooks"))
    }
    commandLine(cargoCmd)
}

// --- Dev mode: stage the just-built cdylib into native/<currentTriple>/,
//     renaming to the JAR resource name (matters on Windows).
val copyNative = tasks.register<Copy>("copyNative") {
    onlyIf { nativeStagingDir == null }
    dependsOn(cargoBuild)
    val t = currentTriple()
    from(File(workspaceRoot, "target/release/${cargoLibName(t)}"))
    into(resourcesNativeRoot.dir(t))
    rename { resourceLibName(t) }
}

// --- Staging mode (CI assemble): copy ALL pre-built native/<triple>/* libs
//     from the staging dir into resources. No cargo, no tests.
val stageNative = tasks.register<Copy>("stageNative") {
    onlyIf { nativeStagingDir != null }
    // config-time guard: prevents File(null, "native") NPE during configuration; onlyIf gates execution
    if (nativeStagingDir != null) {
        from(File(nativeStagingDir, "native"))
        into(resourcesNativeRoot)
    }
}

tasks.named("processResources") { dependsOn(copyNative, stageNative) }

// sourcesJar (generated by the vanniktech publish plugin) includes
// src/main/resources, which stageNative (CI staging mode) and copyNative
// (dev mode) both write to — declare both dependencies so Gradle's
// task-validation check does not fail in either mode.
tasks.withType<Jar>().configureEach {
    if (name == "sourcesJar") {
        dependsOn(stageNative, copyNative)
    }
}

tasks.test {
    dependsOn(copyNative) // dev-mode native; assemble job runs `jar`, not `test`.
    useJUnitPlatform()
    testLogging { showStandardStreams = true }
    // -Xcheck:jni: HotSpot's built-in JNI verifier. It catches the
    // JNI-semantic bug class — invalid/stale handles, local-ref leaks,
    // env misuse across threads — which memory sanitizers
    // cannot see. Violations abort the JVM ("FATAL ERROR in native
    // method"), so regressions fail this gating test job loudly. Cost at
    // our test scale is negligible.
    jvmArgs("-Xcheck:jni")
    // Gate PanicIsolationTest (@EnabledIfSystemProperty) on the probe being built.
    if (jniTestHooks) {
        systemProperty("tst.jniTestHooks", "true")
    }
    // Reflection-based ordinal-boundary tests (MuxerConfigOrdinalTest) call
    // Muxer.nOpen via setAccessible(true). No --add-opens is required: the
    // library JAR is on the classpath (unnamed module), so the module system
    // doesn't restrict deep reflection.
}

// javac (like javadoc below) defaults to the platform charset, which is
// windows-1252 on the Windows CI runner and rejects the UTF-8 arrows / § /
// em-dashes that appear in source comments. Force UTF-8 so main + test
// compilation is deterministic across every platform.
tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}

// --- Completeness guard: in staging mode, fail `jar` if any gating native lib
//     is missing (no silent truncation).
tasks.named<Jar>("jar") {
    doFirst {
        if (nativeStagingDir != null) {
            val missing = gatingTriples.filter {
                !resourcesNativeRoot.dir(it).file(resourceLibName(it)).asFile.exists()
            }
            if (missing.isNotEmpty()) {
                throw GradleException("fat JAR missing gating native libs for: $missing")
            }
            logger.lifecycle("fat JAR native libs: all gating triples present: $gatingTriples")
        }
    }
}

// ---------------------------------------------------------------------------
// Maven Central publishing (org.tstrans:tstrans-jvm). The published main
// artifact is the FAT jar, so publishing runs with -PnativeStagingDir set (the
// `jar` completeness guard above then also protects the publish). Version comes
// from -Pversion=<x.y.z> (CI passes the git tag without its leading `v`).
// ---------------------------------------------------------------------------
group = "org.tstrans"

// Publishing must carry an explicit version; never publish "unspecified".
if (project.version == "unspecified" &&
    gradle.startParameter.taskNames.any {
        it.contains("publishToMavenCentral") || it.contains("publishAllPublicationsTo")
    }) {
    throw GradleException("Set -Pversion=<x.y.z> when publishing (got 'unspecified').")
}

// module-info.java + native methods can make strict javadoc fail; Central only
// requires the javadoc jar to exist, not to be lint-clean. UTF-8 encoding is
// required because source comments contain § and em-dashes (valid UTF-8, but
// javadoc defaults to US-ASCII).
tasks.withType<Javadoc>().configureEach {
    with(options as StandardJavadocDocletOptions) {
        encoding = "UTF-8"       // read sources as UTF-8 (they contain § and em-dashes)
        charSet = "UTF-8"
        docEncoding = "UTF-8"
        addStringOption("Xdoclint:none", "-quiet")
    }
}

mavenPublishing {
    // Explicit (do not rely on auto-detection for the plain `java` plugin):
    // publish the java component + real sources and javadoc jars.
    // Real javadoc jar — the Javadoc task above is configured for UTF-8 so the
    // § / em-dash characters in source comments no longer break generation.
    configure(JavaLibrary(javadocJar = JavadocJar.Javadoc(), sourcesJar = SourcesJar.Sources()))

    // Central Portal, manual release: the upload is validated + staged; a human
    // clicks "Publish" in the Portal UI. (0.36: no SonatypeHost arg needed —
    // Central Portal is the default.)
    publishToMavenCentral(automaticRelease = false)
    signAllPublications()

    coordinates("org.tstrans", "tstrans-jvm", project.version.toString())

    pom {
        name.set("tstrans-jvm")
        description.set(
            "JVM (JDK 17+) bindings for MPEG-TS muxing/demuxing, MISB ST 0601 KLV, " +
                "codec parsing, and SRT/RTP (incl. RTSP) transport"
        )
        inceptionYear.set("2026")
        url.set("https://github.com/aklofas/ts-transformer")
        licenses {
            license {
                name.set("MIT License")
                url.set("https://opensource.org/licenses/MIT")
                distribution.set("repo")
            }
            license {
                name.set("The Apache License, Version 2.0")
                url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
                distribution.set("repo")
            }
        }
        developers {
            developer {
                id.set("aklofas")
                name.set("Andrew Klofas")
                email.set("aklofas@gmail.com")
                url.set("https://github.com/aklofas")
            }
        }
        scm {
            url.set("https://github.com/aklofas/ts-transformer")
            connection.set("scm:git:https://github.com/aklofas/ts-transformer.git")
            developerConnection.set("scm:git:ssh://git@github.com/aklofas/ts-transformer.git")
        }
    }
}
