[package]
name        = "tstrans-srt-sys"
description = "Raw FFI bindings to Haivision libsrt 1.5.x"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
authors.workspace      = true
repository.workspace   = true
links       = "srt"
keywords    = ["srt", "libsrt", "video", "streaming"]
categories  = ["external-ffi-bindings", "multimedia::video"]
exclude = [
    "vendor/srt/apps/",
    "vendor/srt/docs/",
    "vendor/srt/test/",
    "vendor/srt/testing/",
    "vendor/srt/.github/",
    "vendor/srt/examples/",
    "vendor/srt/submodules/",
]

[lib]
name       = "srt_sys"
crate-type = ["rlib"]
doctest    = false

[dependencies]
libc = { workspace = true }

[build-dependencies]
bindgen             = { workspace = true }
cmake               = { workspace = true }
pkg-config          = { workspace = true }
tstrans-mbedtls-src = { path = "../mbedtls-src", version = "0.7.0" }

[dev-dependencies]
libc = { workspace = true }

[features]
default = ["mbedtls"]

# Enable encryption support by building mbedTLS from the vendored source
# tree provided by tstrans-mbedtls-src and linking it into libsrt with
# USE_ENCLIB=mbedtls. Disabling this feature reverts to an
# ENABLE_ENCRYPTION=OFF build.
mbedtls = []
